name: Scheduled Cron Job

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a scheduled task
        run: |
          echo "Scheduled task executed"
